using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Domain.API
{
    public  class XmlDocument
    {
        //const string quote = "\" ahadllao \"";
        public static string GetXmlFile()
        {
            var xmlfile = @"<?xml version=""1.0"" encoding=""utf-8""?>
<MESSAGE TYPE=""RQ"" VERSION=""0200"">
  <HEADER>
    <SERVERSOURCE>DOAPPSERVER2</SERVERSOURCE>
    <SERVICESOURCE>INTERNET.DAL</SERVICESOURCE>
    <SERVICEDESTINATION>SII_PaySvc</SERVICEDESTINATION>
    <CORRELATIONID>2022011407253368849DOf08</CORRELATIONID>
    <CHANNEL>INTERNET</CHANNEL>
    <FUNCTION>GetCities</FUNCTION>
    <LANGUAGE>es-DO</LANGUAGE>
    <COUNTRY-T>DO</COUNTRY-T>
    <SESSIONID>0</SESSIONID>
    <SERVER_IP>192.1.1.23</SERVER_IP>
  </HEADER>
  <CUSTOMERINFO>
    <DOCUMENTTYPE>CEDULA</DOCUMENTTYPE>
    <DOCUMENTNUMBER>00212384831</DOCUMENTNUMBER>
    <USERID>miusuario</USERID>
    <CUSTOMER-TYPE>PERSONAL</CUSTOMER-TYPE>
    <CUSTOMER-SEGMENT>Emergente</CUSTOMER-SEGMENT>
    <PARENT-CUSTOMERID>1</PARENT-CUSTOMERID>
    <CUSTOMERID>2</CUSTOMERID>
    <CHILDDOCUMENTTYPE>N</CHILDDOCUMENTTYPE>
    <CHILDDOCUMENTNUMBER>HOLA</CHILDDOCUMENTNUMBER>
    <CUSTOMERNAME>cliente de prueba</CUSTOMERNAME>
    <CUSTOMERTYPE>PERSONAL</CUSTOMERTYPE>
    <CUSTOMERSEGMENT>Emergente</CUSTOMERSEGMENT>
    <EMAIL>correocliente@gmail.com</EMAIL>
    <CUSTOMERBRANCH>1</CUSTOMERBRANCH>
  </CUSTOMERINFO>
  <DATA>
    <COUNTRY>
      <INTERNAL-ID>644</INTERNAL-ID>
      <CITY-CODE>644</CITY-CODE>
      <DESCRIPCION>USE</DESCRIPCION>
      <CODE-ISO>RD</CODE-ISO>
      <ISO-CODI>DOP</ISO-CODI>
    </COUNTRY>
  </DATA>
      <CITY>
        <INTERNAL-ID>139</INTERNAL-ID>
        <CODE>AA</CODE>
        <COUNTRY-CODE>688</COUNTRY-CODE>
        <STATE>RD</STATE>
        <LONGITUDE>10.1000003814697</LONGITUDE>
        <LATITUDE>48.8330001831055</LATITUDE>
        <TIMEZONE>+01:00</TIMEZONE>
        <DESCRIPCION>SANTO DOMINGO</DESCRIPCION>
        <EXTERNALID>657</EXTERNALID>
        <ENABLED>TRUE</ENABLED>
      </CITY>
</MESSAGE>";

            return xmlfile;
        }
    }
}

